name: runners-de-workflow
on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: mostrar-so
        run: |
          echo "Este trabajo se ejecuta en el Runner de $RUNNER_OS"
          ls -l

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: mostrar-so
        shell: bash
        run: |
          echo "Este trabajo se ejecuta en el Runner de $RUNNER_OS"
          ls -l

  mac-echo:
    runs-on: macos-latest
    steps:
      - name: mostrar-so
        run: |
          echo "Este trabajo se ejecuta en el Runner de $RUNNER_OS"
          ls -l
        